# Cloudflare Workers 项目配置
name = "zk-consulting"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Workers 配置
[assets]
directory = "./out"

# 环境变量
[vars]
NEXT_PUBLIC_SITE_URL = "https://zk-consulting.service-ab5.workers.dev"
NEXT_PUBLIC_REVALIDATE_TIME = "600"
