name = "kz-consulting"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./out"
binding = "ASSETS"

[[routes]]
pattern = "kzconsulting.cn/*"
zone_name = "kzconsulting.cn"

[[routes]]
pattern = "www.kzconsulting.cn/*"
zone_name = "kzconsulting.cn"

# 环境变量配置
[vars]
NEXT_PUBLIC_SITE_URL = "https://kzconsulting.cn"
NEXT_PUBLIC_REVALIDATE_TIME = "600"

# 生产环境变量（需要设置）
# [env.production.vars]
# STRAPI_API_URL = "https://your-strapi-url.com"
# STRAPI_API_TOKEN = "your-token"
